### ISSUE TITLE
vJoy version of Driver (218) does NOT match DLL Version (216)

### ISSUE THREAD

**Issue by ash73** [AndersMalmgren/FreePIE#96]
Just updated to vJoy 2.1.8.31 and FreePIE 1.9.629.0 and I get the above error message in the console.

I was previously using vJoy 0.2.0.4 and FreePIE 1.7.528.0, I uninstalled both before installing the new versions.

I'm using Win 10/64.

**Comment by MarijnS95** [comment]
Well it's not an error, just a warning message (for the interested, see [here](https://github.com/AndersMalmgren/FreePIE/blob/master/FreePIE.Core.Plugins/VJoyPlugin.cs#L89) for details).
Simply means that there might potentially be compatibility issues, so I'd like to know whether you actually have issues using it?

Anders is busy on another project, so I might check out the latest vjoy build and update it.

**Comment by AndersMalmgren** [comment]
Would be cool if you can MarijnS95, im over my head with work on my VR game sadly

**Comment by ash73** [comment]
Thanks for quick reply. Yes it does seem to work ok apart from the warning, just thought I'd let you know.

**Comment by MarijnS95** [comment]
Nice. I'll diff the C# interface sourcecode to see if nothing changed there, update the dll and do some quick checks to ensure it works properly.

**Comment by MarijnS95** [comment]
It should still be compatible and work fine, only a really minor change has been made to the C# wrapper: https://github.com/shauleiz/vJoy/commit/46da21a1976d3e9f13e6d9c38a635c5a4078610f. Since @ash73 already confirmed it works, I only updated the DLL's and quickly checked whether it functions. See PR $97.

Also, the vJoy developer mentioned in the release notes to shift towards [ViGEm](https://github.com/nefarius/ViGEm), might look into that in the future.
